### ISSUE TITLE
Flame animation on close for normal windows crashes Fusilli

### ISSUE THREAD

**Issue by ShadowKyogre** [noodlylight/fusilli#24]
# Steps

1. Enable animation
2. Swap the zoom effect with flames in the default animations configuration
3. Close the configuration window after saving it.

# Backtrace
~~~
backtrace:
#0  0x00007ffa60269401 in _wordcopy_fwd_aligned () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffa60263c35 in __memmove_sse2 () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffa5a159d8d in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#3  0x00007ffa5a1589a5 in ?? () from /usr/lib/xorg/modules/dri/swrast_dri.so
No symbol table info available.
#4  0x00000000004105fc in enableTexture (screen=screen@entry=0x1207430, texture=texture@entry=0x15087e0, filter=filter@entry=COMP_TEXTURE_FILTER_GOOD) at texture.c:422
No locals.
#5  0x000000000042978e in enableFragmentOperationsAndDrawGeometry (mask=655360, filter=1, attrib=0x7ffe066b38b0, texture=0x15087e0, w=0x152df40) at paint.c:1114
        s = <optimized out>
#6  drawWindowTexture (w=0x152df40, texture=0x15087e0, attrib=0x7ffe066b38b0, mask=655360) at paint.c:1182
        filter = 1
#7  0x00007ffa5506e5ff in animDrawWindowTexture (w=0x152df40, texture=<optimized out>, attrib=<optimized out>, mask=<optimized out>) at animation.c:2720
        aw = <optimized out>
        as = 0x13ff050
#8  0x00007ffa55eb48ec in decorDrawWindow (w=0x152df40, transform=<optimized out>, attrib=0x7ffe066b38b0, region=0x63e080 <infiniteRegion>, mask=655360) at decoration.c:201
        wd = 0x150be60
        box = {size = 3, numRects = 1, rects = 0x7ffe066b37c8, extents = {x1 = 585, x2 = 602, y1 = 22, y2 = 341}}
        i = 8
        status = 1
        ds = <optimized out>
        dw = <optimized out>
#9  0x00007ffa552905c0 in wallpaperDrawWindow (w=0x152df40, transform=0x7ffe066b3bc0, attrib=<optimized out>, region=0x14fd7d0, mask=<optimized out>) at wallpaper.c:611
        status = <optimized out>
        s = <optimized out>
        fA = {opacity = 65535, brightness = 65535, saturation = 65535, nTexture = 0, function = {0 <repeats 16 times>}, nFunction = 0, nParam = 0}
        ws = <optimized out>
#10 0x0000000000429fdb in paintWindow (w=0x152df40, attrib=<optimized out>, transform=0x7ffe066b3bc0, region=0x14fd7d0, mask=131072) at paint.c:1266
        fragment = {opacity = 65535, brightness = 65535, saturation = 65535, nTexture = 0, function = {0 <repeats 16 times>}, nFunction = 0, nParam = 0}
        status = <optimized out>
#11 0x00007ffa562c18c5 in movePaintWindow (w=<optimized out>, attrib=<optimized out>, transform=<optimized out>, region=<optimized out>, mask=<optimized out>) at move.c:757
        sAttrib = {opacity = 0, brightness = 16256, saturation = 0, xScale = 1.16018643e+13, yScale = 4.59093403e-41, xTranslate = 7.8472714e-43, yTranslate = 0}
        s = 0x1207430
        status = <optimized out>
        ms = 0x1373bf0
#12 0x00007ffa560bb5ad in resizePaintWindow (w=0x152df40, attrib=<optimized out>, transform=<optimized out>, region=0x14fd7d0, mask=131072) at resize.c:1520
        s = 0x1207430
        status = <optimized out>
        rs = 0x1350340
        rd = 0x1474560
#13 0x00007ffa55aa37dc in cubePaintWindow (w=<optimized out>, attrib=<optimized out>, transform=<optimized out>, region=<optimized out>, mask=<optimized out>) at cube.c:1652
        status = <optimized out>
        s = 0x1207430
        cs = 0x134b710
#14 0x00007ffa55072801 in animPaintWindow (w=0x152df40, attrib=<optimized out>, transform=<optimized out>, region=0x14fd7d0, mask=131072) at animation.c:2842
        wAttrib = {opacity = 65535, brightness = 65535, saturation = 65535, xScale = 1, yScale = 1, xTranslate = 0, yTranslate = 0}
        wTransform = {m = {0.0009765625, 0, 0, 0, -0, -0.00130208337, -0, -0, 0, 0, 1, 0, -0.5, 0.5, -0.866025388, 1}}
        status = <optimized out>
        as = 0x13ff050
        aw = 0x1467f20
#15 0x0000000000427575 in paintOutputRegion (screen=screen@entry=0x1207430, transform=transform@entry=0x7ffe066b3d60, region=region@entry=0x11e9630, mask=mask@entry=9, output=0x13610c0) at paint.c:411
        w = 0x152df40
        c = <optimized out>
        count = <optimized out>
        windowMask = 0
        odMask = <optimized out>
        i = <optimized out>
        fullscreenWindow = <optimized out>
        walk = {fini = 0x0, priv = {ptr = 0x7ffa5506a272, val = 140713145049714, uval = 140713145049714, fptr = 0x7ffa5506a272}, first = 0x4149b0 <walkFirst>, last = 0x4149c0 <walkLast>, next = 0x4149d0 <walkNext>, prev = 0x4149e0 <walkPrev>}
        status = <optimized out>
        withOffset = <optimized out>
        vTransform = {m = {5.32493416e-44, 0, 4.42440462e-35, 4.59149455e-41, 4.58441461e+19, 4.59093403e-41, 4.42434148e-35, 4.59149455e-41, 4.42440002e-35, 4.59149455e-41, 2.9896131e-38, 0, 1.06498683e-43, 0, 0, 0}}
        offX = 1672524169
        offY = 32762
        clip = 0x14fd7d0
        tmpRegion = 0x1464300
#16 0x0000000000428566 in paintOutput (screen=0x1207430, sAttrib=<optimized out>, transform=<optimized out>, region=0x11e9630, output=0x13610c0, mask=9) at paint.c:569
        sTransform = {m = {0.0009765625, 0, 0, 0, -0, -0.00130208337, -0, -0, 0, 0, 1, 0, -0.5, 0.5, -0.866025388, 1}}
#17 0x00007ffa560bbc70 in resizePaintOutput (s=0x1207430, sAttrib=<optimized out>, transform=0x433460 <identity>, region=<optimized out>, output=0x13610c0, mask=<optimized out>) at resize.c:1432
        status = <optimized out>
        rs = 0x1350340
        rd = 0x1474560
#18 0x00007ffa55aa3620 in cubePaintOutput (s=0x1207430, sAttrib=<optimized out>, transform=<optimized out>, region=<optimized out>, output=<optimized out>, mask=<optimized out>) at cube.c:880
        status = 1613140984
        cs = 0x134b710
#19 0x00007ffa5589d003 in rotatePaintOutput (s=0x1207430, sAttrib=0x63dca0 <defaultScreenPaintAttrib>, transform=<optimized out>, region=0x11e9630, output=<optimized out>, mask=9) at rotate.c:583
        status = <optimized out>
        rs = 0x1350ac0
#20 0x00007ffa55495b89 in wsnamesPaintOutput (s=0x1207430, sAttrib=<optimized out>, transform=0x433460 <identity>, region=<optimized out>, output=0x13610c0, mask=<optimized out>) at wsnames.c:406
        status = <optimized out>
        ws = 0x1480c20
#21 0x00007ffa55290481 in wallpaperPaintOutput (s=0x1207430, sAttrib=<optimized out>, transform=<optimized out>, region=<optimized out>, output=<optimized out>, mask=<optimized out>) at wallpaper.c:436
        status = 1613140984
        ws = 0x1382070
#22 0x00007ffa5507108e in animPaintOutput (s=0x1207430, sAttrib=0x63dca0 <defaultScreenPaintAttrib>, transform=<optimized out>, region=<optimized out>, output=<optimized out>, mask=<optimized out>) at animation.c:4202
        status = <optimized out>
        as = 0x13ff050
        w = <optimized out>
#23 0x00000000004117e9 in paintScreen (s=0x1207430, outputs=<optimized out>, numOutput=<optimized out>, mask=<optimized out>) at display.c:873
        r = {x = <optimized out>, y = -132, width = 1024, height = 768}
        i = <optimized out>
#24 0x00007ffa55aa351a in cubePaintScreen (s=0x1207430, outputs=0x13610c0, numOutputs=1, mask=3) at cube.c:853
        x = 0
        progress = 0
        cs = 0x134b710
#25 0x0000000000411cf1 in eventLoop () at display.c:1093
        option_force_independent_output_painting = <optimized out>
        event = {type = 91, xany = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862}, xkey = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, root = 6291831, subwindow = 0, time = 1206788, x = 0, y = 4063846, x_root = 0, y_root = 5571174, state = 0, keycode = 0, same_screen = 0}, xbutton = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, root = 6291831, subwindow = 0, time = 1206788, x = 0, y = 4063846, x_root = 0, y_root = 5571174, state = 0, button = 0, same_screen = 0}, xmotion = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, root = 6291831, subwindow = 0, time = 1206788, x = 0, y = 4063846, x_root = 0, y_root = 5571174, state = 0, is_hint = 0 '\000', same_screen = 0}, xcrossing = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, root = 6291831, subwindow = 0, time = 1206788, x = 0, y = 4063846, x_root = 0, y_root = 5571174, mode = 0, detail = 0, same_screen = 0, focus = 0, state = 1616366456}, xfocus = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, mode = 6291831, detail = 0}, xexpose = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, x = 6291831, y = 0, width = 0, height = 0, count = 1206788}, xgraphicsexpose = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, drawable = 23068862, x = 6291831, y = 0, width = 0, height = 0, count = 1206788, major_code = 0, minor_code = 0}, xnoexpose = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, drawable = 23068862, major_code = 6291831, minor_code = 0}, xvisibility = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, state = 6291831}, xcreatewindow = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, parent = 23068862, window = 6291831, x = 0, y = 0, width = 1206788, height = 0, border_width = 0, override_redirect = 4063846}, xdestroywindow = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831}, xunmap = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831, from_configure = 0}, xmap = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831, override_redirect = 0}, xmaprequest = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, parent = 23068862, window = 6291831}, xreparent = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831, parent = 0, x = 1206788, y = 0, override_redirect = 0}, xconfigure = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831, x = 0, y = 0, width = 1206788, height = 0, border_width = 0, above = 23928010130325504, override_redirect = 0}, xgravity = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831, x = 0, y = 0}, xresizerequest = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, width = 6291831, height = 0}, xconfigurerequest = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, parent = 23068862, window = 6291831, x = 0, y = 0, width = 1206788, height = 0, border_width = 0, above = 23928010130325504, detail = 0, value_mask = 0}, xcirculate = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, event = 23068862, window = 6291831, place = 0}, xcirculaterequest = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, parent = 23068862, window = 6291831, place = 0}, xproperty = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, atom = 6291831, time = 0, state = 1206788}, xselectionclear = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, selection = 6291831, time = 0}, xselectionrequest = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, owner = 23068862, requestor = 6291831, selection = 0, target = 1206788, property = 17454085665980416, time = 23928010130325504}, xselection = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, requestor = 23068862, selection = 6291831, target = 0, property = 1206788, time = 17454085665980416}, xcolormap = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, colormap = 6291831, new = 0, state = 0}, xclient = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, message_type = 6291831, format = 0, data = {b = "\004j\022\000\000\000\000\000\000\000\000\000f\002>\000\000\000\000", s = {27140, 18, 0, 0, 0, 0, 614, 62, 0, 0}, l = {1206788, 17454085665980416, 23928010130325504, 0, 0}}}, xmapping = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, request = 6291831, first_keycode = 0, count = 0}, xerror = {type = 91, display = 0xa5a, resourceid = 0, serial = 18830000, error_code = 190 '\276', request_code = 0 '\000', minor_code = 96 '`'}, xkeymap = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, window = 23068862, key_vector = "w\001`", '\000' <repeats 13 times>, "\004j\022\000\000\000\000\000\000\000\000\000f\002>"}, xgeneric = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, extension = 23068862, evtype = 0}, xcookie = {type = 91, serial = 2650, send_event = 0, display = 0x11f52b0, extension = 23068862, evtype = 0, cookie = 6291831, data = 0x0}, pad = {140711718551643, 2650, 0, 18830000, 23068862, 6291831, 0, 1206788, 17454085665980416, 23928010130325504, 0, 0, 140713334918008, -4, 22177632, -4, 140713237337896, -4, 0, -4, 140713237458624, -4, 0, -4}}
        timeDiff = <optimized out>
        tv = {tv_sec = 1433340053, tv_usec = 868158}
        d = 0x63e160 <display>
        s = 0x1207430
        w = <optimized out>
        t = <optimized out>
        time = <optimized out>
        timeToNextRedraw = 3
        damageMask = <optimized out>
        mask = 3
#26 0x000000000040dd86 in main (argc=1, argv=0x7ffe066b4348) at main.c:347
        displayName = <optimized out>
        i = <optimized out>
        disableSm = <optimized out>
        clientId = <optimized out>
~~~

# Config File
banana.xml from virtual machine I'm testing fusilli in: http://dpaste.com/31XQKSB (because putting it inline with the issue would be weird, replace the wallpaper pixmaps with your own for testing)

**Comment by noodlylight** [comment]
Thanks for the extremely detailed issue.

Plugin animation has several issues/bugs, I did a bad job porting it to fusilli. I will need to start from scratch.

Unfortunately it will take me some time to fix.
